## Tier 1. Module 2: Mathematics for Computer Science
## Topic 3 - Vectors on the plane and in space
## Homework

4 points are given: $M_0(0, 0, 0), M_1(1, \frac{1}{3}, 0), M_2(0, 2, \frac{1}{4}), M_3(\frac{1}{2}, \frac{1}{2}, 1)$.

Also given are 3 vectors that define a parallelepiped with the specified points:
- $\overline{a}=\overline{M_0M_1}$
- $\overline{b}=\overline{M_0M_2}$
- $\overline{c}=\overline{M_0M_3}$

Calculate the coordinates of the vectors through the given points.
Calculate the volume, the area of the entire surface of the parallelepiped and the angles between the edges of the parallelepiped, the coordinates of the remaining vertices of the parallelepiped.

$\overline{a} = M_1 - M_0 = \left (\begin{array}{cc}
1\\
\frac{1}{3}\\
0
\end{array}\right)
\\
\overline{b} = M_2 - M_0 = \left (\begin{array}{cc}
0\\
2\\
\frac{1}{4}
\end{array}\right)
\\
\overline{c} = M_3 - M_0 = \left (\begin{array}{cc}
\frac{1}{2}\\
\frac{1}{2}\\
1
\end{array}\right)
$

#### 1 - Coordinates of vectors

In [4]:
import numpy as np

M0 = np.array([0, 0, 0])
M1 = np.array([1, 1/3, 0])
M2 = np.array([0, 2, 1/4])
M3 = np.array([1/2, 1/2, 1])

a = M1 - M0
b = M2 - M0
c = M3 - M0

print(a, b, c)

[1.         0.33333333 0.        ] [0.   2.   0.25] [0.5 0.5 1. ]


In [5]:
import plotly.graph_objects as go

# Creating an array of points in a plane
point_in_plane = np.array([0, 0, 0])
points_on_plane = np.column_stack((a, b, c)) + point_in_plane

# Creating a "Figure" object for 3D graphics
fig = go.Figure()

# Adding vectors to a graph
fig.add_trace(go.Scatter3d(x=[0, a[0]], y=[0, a[1]], z=[0, a[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='red'), name='Vector A'))
fig.add_trace(go.Scatter3d(x=[0, b[0]], y=[0, b[1]], z=[0, b[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='blue'), name='Vector B'))
fig.add_trace(go.Scatter3d(x=[0, c[0]], y=[0, c[1]], z=[0, c[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='green'), name='Vector C'))

# Setting the graphics view
fig.update_layout(scene=dict(aspectmode='data'))
fig.update_layout(scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'))
fig.update_layout(title='Three vectors in 3D space')

fig.show()

#### 2 - Volume of a parallelepiped

$
V = \left|\left(\vec{a}, \vec{b}, \vec{c}\right)\right| = \left|\begin{array}{cc}
1 & \frac{1}{3} & 0 \\
0 & 2 & \frac{1}{4} \\
\frac{1}{2} & \frac{1}{2} & 1
\end{array}\right| = 1 \cdot 2 \cdot 1 + \frac{1}{3} \cdot \frac{1}{4} \cdot \frac{1}{2} + 0 \cdot 0 \cdot \frac{1}{2} - \frac{1}{2} \cdot 2 \cdot 0 - 1 \cdot \frac{1}{2} \cdot \frac{1}{4} - 0 \cdot \frac{1}{3} \cdot 1 = 1\frac{11}{12} = 1.92 \left(од^{3}\right)
$

In [6]:
V = np.linalg.det(np.dstack([a,b,c]))
V

array([1.91666667])

#### 3 - The total surface area of the parallelepiped

$
S = 2\left|\vec{a} \times \vec{b} \right| + 2\left|\vec{b} \times \vec{c} \right| + 2\left|\vec{c} \times \vec{a} \right| = 2\left (\begin{array}{cc}
\vec{i} & \vec{j} & \vec{k} \\
1 & \frac{1}{3} & 0 \\
0 & 2 & \frac{1}{4}
\end{array}\right) +
2\left (\begin{array}{cc}
\vec{i} & \vec{j} & \vec{k} \\
0 & 2 & \frac{1}{4} \\
\frac{1}{2} & \frac{1}{2} & 1
\end{array}\right) +
2\left (\begin{array}{cc}
\vec{i} & \vec{j} & \vec{k} \\
\frac{1}{2} & \frac{1}{2} & 1 \\
1 & \frac{1}{3} & 0
\end{array}\right) = \\
= 2\sqrt{\left( \frac{1}{12} \right)^{2} + \left( \frac{-1}{4} \right)^{2} + \left( 2 \right)^{2}} +
2\sqrt{\left( 1\frac{7}{8} \right)^{2} + \left( \frac{1}{8} \right)^{2} + \left( -1 \right)^{2}} +
2\sqrt{\left( \frac{-1}{3} \right)^{2} + \left( 1 \right)^{2} + \left( \frac{-1}{3} \right)^{2}} = \\
= 2 \cdot (2.017 + 2.129 + 1.106) = 10.50 \left(од^{2}\right)
$

In [7]:
S = 2 * (np.linalg.norm(np.cross(a, b)) + np.linalg.norm(np.cross(b, c)) + np.linalg.norm(np.cross(c, a)))
S

10.50300259735527

#### 4 - Angles between the edges of a parallelepiped

$
\angle(a, b) = arccos(cos\alpha) = arccos\left( \frac{\vec{a}\vec{b}}{|\vec{a}||\vec{b}|} \right) = arccos\left( \frac{1 \cdot 0 + \frac{1}{3} \cdot 2 + 0 \cdot \frac{1}{4}}{\sqrt{1^{2} + \left( \frac{1}{3} \right)^{2} + 0^{2}}
\sqrt{0^{2} + 2^{2} + \left( \frac{1}{4}\right)^{2}}} \right) = arccos(0.31) = 71.7° \\
\angle(a, c) = arccos(cos\beta) = arccos\left( \frac{\vec{a}\vec{c}}{|\vec{a}||\vec{c}|} \right) = arccos\left( \frac{1 \cdot \frac{1}{2} + \frac{1}{3} \cdot \frac{1}{2} + 0 \cdot 1}{\sqrt{1^{2} + \left( \frac{1}{3} \right)^{2} + 0^{2}}
\sqrt{\left( \frac{1}{2} \right)^{2} + \left( \frac{1}{2} \right)^{2} + 1^{2}}} \right) = arccos(0.52) = 58.9° \\
\angle(b, c) = arccos(cos\phi) = arccos\left( \frac{\vec{b}\vec{c}}{|\vec{b}||\vec{c}|} \right) = arccos\left( \frac{0 \cdot \frac{1}{2} + 2 \cdot \frac{1}{2} + \frac{1}{4} \cdot 1}{\sqrt{0^{2} + 2^{2} + \left( \frac{1}{4} \right)^{2}}
\sqrt{\left( \frac{1}{2} \right)^{2} + \left( \frac{1}{2} \right)^{2} + 1^{2}}} \right) = arccos(0.51) = 59.6° \\
$

In [8]:
angle_ab = np.degrees(np.arccos(a @ b / np.linalg.norm(a) / np.linalg.norm(b)))
angle_ac = np.degrees(np.arccos(a @ c / np.linalg.norm(a) / np.linalg.norm(c)))
angle_bc = np.degrees(np.arccos(b @ c / np.linalg.norm(b) / np.linalg.norm(c)))
print(angle_ab, angle_ac, angle_bc)

71.71246981426138 58.90906964232697 59.57768271314148


In [9]:
b @ c / np.linalg.norm(b) / np.linalg.norm(c)

0.5063696835418334

#### 5 - Coordinates of the remaining vertices of the parallelepiped

$
M_4 = \vec{a} + \vec{b} = \left(1, \frac{1}{3}, 0 \right) + \left(0, 2, \frac{1}{4} \right) = \left(1, 2\frac{1}{3}, \frac{1}{4} \right)\\
M_5 = \vec{a} + \vec{c} = \left(1, \frac{1}{3}, 0 \right) + \left(\frac{1}{2}, \frac{1}{2}, 1 \right) = \left(1\frac{1}{2}, \frac{5}{6}, 1 \right)\\
M_6 = \vec{b} + \vec{c} = \left(0, 2, \frac{1}{4} \right) + \left(\frac{1}{2}, \frac{1}{2}, 1 \right) = \left(\frac{1}{2}, 2\frac{1}{2}, 1\frac{1}{4} \right)\\
M_7 = M_4 + \vec{c} = \left(1, 2\frac{1}{3}, \frac{1}{4} \right) + \left(\frac{1}{2}, \frac{1}{2}, 1 \right) = \left(1\frac{1}{2}, 2\frac{5}{6}, 1\frac{1}{4} \right)
$

In [10]:
M4 = a + b
M4

array([1.        , 2.33333333, 0.25      ])

In [11]:
M5 = a + c
M5

array([1.5       , 0.83333333, 1.        ])

In [12]:
M6 = b + c
M6

array([0.5 , 2.5 , 1.25])

In [13]:
M7 = M4 + c
M7

array([1.5       , 2.83333333, 1.25      ])

In [14]:
# Creating an array of points in a plane
point_in_plane = np.array([0, 0, 0])
points_on_plane = np.column_stack((a, b, c)) + point_in_plane

# Creating a "Figure" object for 3D graphics
fig = go.Figure()

# Adding vectors to a graph
fig.add_trace(go.Scatter3d(x=[0, a[0]], y=[0, a[1]], z=[0, a[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='red'), name='Vector M0-M1'))
fig.add_trace(go.Scatter3d(x=[M4[0], b[0]], y=[M4[1], b[1]], z=[M4[2], b[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='red'), name='Vector M2-M4'))
fig.add_trace(go.Scatter3d(x=[M5[0], c[0]], y=[M5[1], c[1]], z=[M5[2], c[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='red'), name='Vector M3-M5'))
fig.add_trace(go.Scatter3d(x=[M7[0], M6[0]], y=[M7[1], M6[1]], z=[M7[2], M6[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='red'), name='Vector M6-M7'))

fig.add_trace(go.Scatter3d(x=[0, b[0]], y=[0, b[1]], z=[0, b[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='blue'), name='Vector M0-M2'))
fig.add_trace(go.Scatter3d(x=[M4[0], a[0]], y=[M4[1], a[1]], z=[M4[2], a[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='blue'), name='Vector M1-M4'))
fig.add_trace(go.Scatter3d(x=[M6[0], c[0]], y=[M6[1], c[1]], z=[M6[2], c[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='blue'), name='Vector M3-M6'))
fig.add_trace(go.Scatter3d(x=[M7[0], M5[0]], y=[M7[1], M5[1]], z=[M7[2], M5[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='blue'), name='Vector M5-M7'))

fig.add_trace(go.Scatter3d(x=[0, c[0]], y=[0, c[1]], z=[0, c[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='green'), name='Vector M0-M3'))
fig.add_trace(go.Scatter3d(x=[M5[0], a[0]], y=[M5[1], a[1]], z=[M5[2], a[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='green'), name='Vector M1-M5'))
fig.add_trace(go.Scatter3d(x=[M6[0], b[0]], y=[M6[1], b[1]], z=[M6[2], b[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='green'), name='Vector M2-M6'))
fig.add_trace(go.Scatter3d(x=[M7[0], M4[0]], y=[M7[1], M4[1]], z=[M7[2], M4[2]],
                           mode='lines+markers', marker=dict(size=5), line=dict(color='green'), name='Vector M4-M7'))


# Setting the graphics view
fig.update_layout(scene=dict(aspectmode='data'))
fig.update_layout(scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'))
fig.update_layout(title='All vectors in 3D space')

fig.show()